id = "luau"
name = "Luau"
version = "0.3.6"
schema_version = 1
authors = ["teapo <4teapo@gmail.com>"]
description = "Luau support."
repository = "https://github.com/4teapo/zed-luau"

[language_servers.luau-lsp]
name = "Luau LSP"
language = "Luau"

[grammars.luau]
repository = "https://github.com/4teapo/tree-sitter-luau"
commit = "14cff6d48536f44819453f00a48546e1ef1e970f"
