id = "luau"
name = "Luau"
version = "0.3.3"
schema_version = 1
authors = ["teapo <4teapo@gmail.com>"]
description = "Luau support."
repository = "https://github.com/4teapo/zed-luau"

[language_servers.luau-lsp]
name = "Luau LSP"
language = "Luau"

[grammars.luau]
repository = "https://github.com/4teapo/tree-sitter-luau"
commit = "0d66daa8a247fad86c19964dd2406a8646cac966"
